### Seleccionar persistencia Mercado Pago
GET http://localhost:3010/persistence/obtenerPersistencia

### Seleccionar tokens de persistencia
GET http://localhost:3010/persistence/obtenerTOKEN

### Insertar persistencia
POST http://localhost:3010/persistence/insertarPersistencia
Content-Type: application/json

{
  "nombre_cliente": "Cliente de prueba Mercado Pago",
  "access_token": "ACCESS_TOKEN_FICTICIO_PARA_PRUEBAS"
}

### Actualizar persistencia
POST http://localhost:3010/persistence/actualizar
Content-Type: application/json

{
  "nombre_cliente": "Cliente de prueba actualizado",
  "access_token": "ACCESS_TOKEN_FICTICIO_ACTUALIZADO",
  "id_mercadoPago_persistence": 1
}

### Actualizar estado pasarela
POST http://localhost:3010/persistence/actualizarEstado
Content-Type: application/json

{
  "estado_pasarela": 1,
  "id_mercadoPago_persistence": 1
}